### ISSUE TITLE
Support for Purity API versions 2.0+

### ISSUE THREAD

**Issue by jaymzmac** [PureStorage-OpenConnect/rest-client#24]
Hi,

Is there any work being done to add support for Purity API versions 2.0+? 

It would be great if we could use this SDK to use the new and improved REST API version, not least to be able to authenticate using the more secure OAuth2 method.

**Comment by mksteele** [comment]
Former Pure employee - things might have changed.

There's a different, new package here that works for 2.0+: https://github.com/PureStorage-OpenConnect/py-pure-client

The good news: it's the latest and greatest, and supports OAuth2 and the API version you care about.

The bad news: You'll have to rewrite your application to use the new package instead of the old one.
